language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "axzW/XG0oomEBhNUAjsAtp/X61LvnlzhZUCbA9NRASGqdpSMeKF6mWnczLOtto0vWMK4Cn8UV4ESYhhnroG4pKkIpz3aP8jl6sOu725V/uSlSjQtFLrFNeOWdbKUEDVi1ZDlSovXbONcCF4ewt1fkCPHykJOLWKZkJt5dZjoPezQDVNZ3p8yS+7XOJ5ek8TEr9z7J/+fo+w7JedC2ykl3japVJL9hZ0DtQQFWvTZLU2rK9JCQPHRjcaAgsGBtRLc+J+hVVYqyjFGdw8O4qMGGnMPS28awm04ctZduPLtpHMoiTl3wj/Mx/8vBAOnRq5wGoWDDb3PZR06gluxmNukyR3Fh+FcdN/s586Z89hdwHqJ/1dAz9sGxLreziizM3AlBHvHZzGVd/lihXn2LuMdFt3xylhrZuvP3SJMOJGCdzOoMlstuH4HlO6BLfBaUkTPCDQ1Nj8QJlzETqv2xt8nZFxd9k49MzNZLtdZFFT1DF+hdFMmYqSehgkK2YO25ewF5j4NcTyBtvFwkrwq0EXyC2r+O3QS4QEXyOlaSNbC7MyKFseJzfwV2z5n4Cs5tvAdh1UqYiIdOrJNQBgjK7E5jdAJIaHokjMP7psNoDI3Gtzksn051Y3i9AZnAKwSEKaaG3+HJ4mYAxCIgz1jDpPRNNQOYjjeBt7cixYhiYFoFtI="
